GET http://localhost:32241/api/platforms/

###
GET http://localhost:32241/api/platforms/1

###
POST http://localhost:32241/api/platforms/ HTTP/1.1
content-type: application/json

{
    "name": "JVM",
    "publisher": "Oracle",
    "cost": "free"
}